"""
Thermal averaging and polarization analysis from quantum eigenstate data.

This script analyzes eigenstates generated by `generate.py` to compute
thermal averages of position and polarization as a function of electric field.
Optional analysis can estimate the harmonic frequency of the potential well
and suggest a mass that reproduces a target polar mode frequency.

## FUNCTIONALITY

1. Loads simulation results from `all_simulation_data.h5`

   * Eigenenergies and eigenfunctions
   * Physical parameters: mass, number of states, effective charge (z*), volume
   * Electric field values

2. Loads the potential energy grid from `interpolated_potential.txt`.

3. Loads analysis parameters from `PARAMS_anal.json`.

4. Computes thermal averages

   * Full thermal average ⟨x⟩
   * Optional partial average ⟨x⟩ within [x_min, x_max]

5. Converts ⟨x⟩ to polarization using
   P = ⟨x⟩ / conv_P2x

6. Plots polarization vs electric field.

7. Optionally plots eigenstates contributing ≥99% of the thermal probability
   at a user-selected electric field.

8. Optional frequency analysis (enabled by `do_frequency_analysis`)

   * Computes ⟨V''⟩ using the ground-state wavefunction
   * Estimates harmonic frequency of the potential well
   * Compares with the E1–E0 excitation spacing
   * Reports anharmonicity ratio
   * If `polar_mode_freq_THz` is provided, suggests a mass reproducing
     that frequency (output in me and amu).

## INPUT FILES

all_simulation_data.h5
Eigenvalues, eigenvectors, and simulation parameters.

interpolated_potential.txt
Potential grid with columns:
x   V(x)

PARAMS_anal.json
Analysis parameters, e.g.
{
"Temp": float,
"x_min": float (optional),
"x_max": float (optional),
"Field_to_plot": float (optional),
"do_frequency_analysis": bool (optional),
"polar_mode_freq_THz": float (optional)
}

## OUTPUT

Polarization_vs_Field_equil.png
Polarization vs electric field.

Polarization_vs_Field_equil.txt
Field(V/nm)   P_full(C/m²)

Eigenstates_99percent.png
Eigenstates contributing ≥99% thermal probability (optional).

prob_density_selected_states.txt
Probability densities of selected eigenstates (optional).

## NOTES

Eigenvalues used in plots are shifted so the ground-state energy is zero,
so reported frequencies correspond to excitations relative to the ground state.
"""



import numpy as np
import h5py
import json
import matplotlib.pyplot as plt

# Constants
k_B = 8.617333262145e-5  # eV/K

# Load temperature from PARAMS_anal.json
with open("PARAMS_anal.json", "r") as f_json:
    params_anal = json.load(f_json)
Temp = params_anal["Temp"]
polar_mode_freq = params_anal.get("polar_mode_freq_THz", None)
do_frequency_analysis = params_anal.get("do_frequency_analysis", False)
# Target relaxation rate from experiment / dynamics fit (THz)
gamma_target_thz = params_anal.get("gamma_target_thz", None)



# Load x_int  and v_int from interpolated_potential.txt

data_interp = np.loadtxt("interpolated_potential.txt")
x_int = data_interp[:, 0]
v_int = data_interp[:, 1]




# d2Vdx2 = np.gradient(np.gradient(v_int, x_int), x_int)
# # Plot the result
# plt.figure(figsize=(7,5))
# plt.plot(x_int, d2Vdx2, label=r"$d^2V/dx^2$")
# plt.xlabel("x")
# plt.ylabel(r"$d^2V/dx^2$")
# plt.title("Second Derivative of Interpolated Potential")
# plt.grid(True)
# plt.legend()
# plt.tight_layout()
# plt.show()

x_min = params_anal.get("x_min", x_int.min())
x_max = params_anal.get("x_max", x_int.max())
#Field_to_plot = params_anal.get("Field_to_plot", None)  # <-- Add this line
Field_to_plot = float(params_anal.get("Field_to_plot", None)) if "Field_to_plot" in params_anal else None



def comp_X_av_partial(e_tmp, phi_tmp, x_min, x_max):
    mask = (x_int >= x_min) & (x_int <= x_max)
    # Compute full thermal probability density over all states and positions
    prob_density = np.zeros_like(x_int)
    Z = 0.
    e_tmp=e_tmp-e_tmp[0]
    for i in range(num_sol):
        prob = np.exp(-e_tmp[i] / (k_B * Temp))
        Z += prob
        prob_density += prob * (phi_tmp[:, i] ** 2)
    prob_density /= Z  # Normalize full probability density

    # Compute partial trace on interval
    partial_prob = np.sum(prob_density[mask])
    total_prob = np.sum(prob_density)
#    print(partial_prob/total_prob) 
    if partial_prob/total_prob > 0.001:
        # Compute partial average <x> on the interval weighted by partial prob density
        X_av_partial = np.sum(x_int[mask] * prob_density[mask]) / partial_prob
        return X_av_partial
    else:
        return None  # No weight in this interval

    # Function to compute X_av at a given field
def comp_X_av(e_tmp, phi_tmp):
    Z = 0.
    X_av = 0.
    for i in range(num_sol):
        prob = np.exp(-(e_tmp[i]-e_tmp[0]) / (k_B * Temp))
        Z += prob
        X_av += prob * np.sum(x_int * phi_tmp[:, i] ** 2)
    return X_av / Z

def compute_ground_state_Vpp_and_frequency(
        x_int, v_int, eigen_data_group, mass,
        polar_mode_freq=None,
        field_idx=None,
        field_value=None):
    """
    Compute <V''(x)> using the ground state at a given electric field
    and estimate harmonic frequency.
    """

    dx = x_int[1] - x_int[0]

    # ------------------------------------
    # 5-point stencil second derivative
    # ------------------------------------
    d2Vdx2 = np.zeros_like(v_int)

    for i in range(2, len(v_int)-2):
        d2Vdx2[i] = (
            -v_int[i+2] + 16*v_int[i+1] - 30*v_int[i]
            + 16*v_int[i-1] - v_int[i-2]
        ) / (12 * dx**2)

    valid = slice(2, -2)

    d2Vdx2_valid = d2Vdx2[valid]

    # ------------------------------------
    # Select field
    # ------------------------------------
    if field_idx is None:
        field_idx = int(np.argmin(np.abs(field_values)))

    group = eigen_data_group[f'field_{field_idx:03d}']

    energies = group['energies'][:]
    energies = energies - energies[0]

    eigenvectors = group['eigenvectors'][:]

    psi0 = eigenvectors[:,0]
    psi0_valid = psi0[valid]

    prob = psi0_valid**2

    # ------------------------------------
    # Expectation value <V''>
    # ------------------------------------
    exp_Vpp = np.sum(prob * d2Vdx2_valid) * dx / np.sum(prob * dx)

    # ------------------------------------
    # Harmonic frequency
    # ------------------------------------
    conver = 419.3
    omega = conver*np.sqrt(exp_Vpp / mass)
    nu = omega / (2*np.pi)

    # ------------------------------------
    # Frequency from excitation
    # ------------------------------------
    deltaE = energies[1] - energies[0]

    tol = 1e-4
    degenerate = False

    if abs(deltaE) < tol:
        degenerate = True
        deltaE_original = deltaE
        deltaE = energies[2] - energies[0]

    freq_spacing_thz = deltaE * 1520 / (2*np.pi)

    ratio = nu / freq_spacing_thz

    # ------------------------------------
    # Output
    # ------------------------------------
    if field_value is None:
        print("\n--- Frequency analysis at zero field ---")
    else:
        print(f"\n--- Frequency analysis at E = {field_value:.3f} V/nm ---")

    print(
        f"Harmonic freq (<V''>): {nu:.6f} THz | "
        f"Freq from ΔE: {freq_spacing_thz:.6f} THz | "
        f"Anharmonicity ratio: {ratio:.3f}"
    )

    if degenerate:
        print(
            f"Ground state degenerate within tol={tol} eV "
            f"(E1-E0={deltaE_original:.3e})."
        )
        print("Used E2-E0 for estimate.")

    # ------------------------------------
    # Suggested mass
    # ------------------------------------
    if polar_mode_freq is not None:
        target_nu = polar_mode_freq
        me_per_amu = 1822.888486

        suggested_mass_me = exp_Vpp / ((2*np.pi*target_nu/419.3)**2)
        suggested_mass_amu = suggested_mass_me / me_per_amu

        print("\nTarget polar mode frequency:", target_nu, "THz")
        print(f"Suggested mass: {suggested_mass_amu:.6f} amu = {suggested_mass_me:.2f} me")

    return exp_Vpp, nu



# Load everything from the HDF5 file
with h5py.File("all_simulation_data.h5", "r") as f:
    mass = f.attrs['mass']
    n = int(f.attrs['n'])
    num_sol = int(f.attrs['num_sol'])
    z_star = f.attrs['Star']
    Vol = f.attrs['Vol']

    field_values = f['field_values'][:]
    eigen_data_group = f['eigen_data']
    conv_P2x = Vol * 0.01 / (z_star * 1.6) 
    



    # Loop over all fields and compute X_av
    X_av_list = []
    X_av_part_list = []
    field_values_part = []  # for partial points where trace > 0
    for i in range(len(field_values)):
        group = eigen_data_group[f'field_{i:03d}']
        energies = group['energies'][:]
 #       energies = energies - energies[0]
        eigenvectors = group['eigenvectors'][:]
        X_av = comp_X_av(energies, eigenvectors)
        X_av_part = comp_X_av_partial(energies, eigenvectors, x_min, x_max)
        if X_av_part is not None:
            X_av_part_list.append(X_av_part)
            field_values_part.append(field_values[i])
            # else skip
        X_av_list.append(X_av)
#        X_av_part_list.append(X_av_part)



    # Optional: Plot selected eigenstates at a specific field value
    #if "Field_to_plot" in params_anal:
    if Field_to_plot is not None:
        E_plot = Field_to_plot
        idx_closest = int(np.argmin(np.abs(field_values - E_plot)))  # cast to plain int
        group_name = f'field_{idx_closest:03d}'  # this will now be a valid string
        group = eigen_data_group[group_name]
        
        # Your plotting logic here
       # E_plot = params_anal["Field_to_plot"]
       # idx_closest = np.argmin(np.abs(field_values - E_plot))
       # group = eigen_data_group[f'field_{idx_closest:03d}']
        energies = group['energies'][:]
        energies = energies - energies[0]
        eigenvectors = group['eigenvectors'][:]
    
      

        # ------------------------------------
        # LO-like decay-rate analysis
        # ------------------------------------
        num_states = len(energies)

        gamma_mat = np.zeros((num_states, num_states))

        h_eVfs = 4.135667696  # eV·fs

        for n in range(num_states):
            for k in range(n + 1, num_states):

                deltaE = energies[k] - energies[n]

                omega = np.abs(deltaE) #/ h_eVfs

                # upward transition
                gamma_mat[k, n] = omega * np.exp(-deltaE / (k_B * Temp))

                # downward transition
                gamma_mat[n, k] = omega
                
 
        # # total outflow rate of each state
        # gamma_out = np.sum(gamma_mat, axis=0)

        # # arithmetic average over all states
        # avg_decay_rate = 2*np.mean(gamma_out) # factor of 2 is to account for the factor of 2 in LO decay rate

        # # convert 1/fs -> THz
        # avg_decay_rate_thz = avg_decay_rate *   1520 / (2 * np.pi)

        # print(
        #     f"\nAverage LO-like decay rate: "
        #     f"{avg_decay_rate:.6e} 1/fs "
        #     f"= {avg_decay_rate_thz:.6f} THz"
        # )    
    
    
    
        # Compute Boltzmann weights
        boltz_weights = np.exp(-energies / (k_B * Temp))
        Z = np.sum(boltz_weights)
        probs = boltz_weights / Z
    
        # Sort states by descending probability
        sorted_indices = np.argsort(probs)[::-1]
        cumulative_prob = 0.
        selected_states = []
        for idx in sorted_indices:
            cumulative_prob += probs[idx]
            selected_states.append(idx)
            if cumulative_prob >= 0.995:
                break
    
        # Plot selected eigenstates with vertical shift by energy
        plt.figure(figsize=(8, 6))
        psi2_matrix = []
        for idx in selected_states:
            psi = eigenvectors[:, idx]
            prob_density = psi**2
            psi2_matrix.append(prob_density)

            
#            # Save the probability density to a file
#            np.savetxt(
#                f"prob_density_state_{idx}.txt",
#                np.column_stack([x_int, prob_density]),
#                header="x  psi_squared"
#                )

            
            prob_density /= np.max(prob_density)  # Normalize for visibility
            vertical_shift = energies[idx]        # Shift by eigenenergy (in eV)
            plt.plot(x_int, prob_density + vertical_shift, 
                     label=f"$E_{{{idx}}}$ = {energies[idx]:.3f} eV, p = {probs[idx]*100:.1f}%")
        
        plt.xlabel("x")
        plt.ylabel(r"$|\psi(x)|^2 + E$")
        plt.title(f"Eigenstates Contributing ≥99% at E = {field_values[idx_closest]:.0f} kV/cm, T = {Temp} K")
        plt.legend()
        plt.grid(True)
        plt.tight_layout()
        plt.savefig("Eigenstates_99percent.png", dpi=300)
        plt.show()
        
        print("\nNOTE:")
        print("Eigenvalues shown below are shifted so that the ground state energy is zero.")
        print("This removes the absolute zero-point energy and shows only excitation energies.")
        print("All frequencies therefore correspond to transitions relative to the ground state.")
        print("\nAll eigenvalues (index, eV, 2π·THz, THz, ΔTHz):")
   #     ev_to_hz = 2.417989e14  # 1 eV = 2.417989e14 Hz
        prev_freq_thz = None
        
        for i, val in enumerate(energies):
            freq_2pi_thz = val*1520 
            freq_thz = freq_2pi_thz / (2 * np.pi) #freq_hz / (2 * np.pi * 1e12)
        
            delta_thz = 0.0 if prev_freq_thz is None else (freq_thz - prev_freq_thz)
        
            print(f"{i:3d}  {val:10.6f}  {freq_2pi_thz:10.6f}  {freq_thz:10.6f}  {delta_thz:10.6f}")
        
            prev_freq_thz = freq_thz
        
        # print("\nAll eigenvalues (index, eV, 2π·THz, THz):")
        # ev_to_hz = 2.417989e14  # 1 eV = 2.417989e14 Hz
        # for i, val in enumerate(energies):
        #     freq_hz = val * ev_to_hz
        #     freq_2pi_thz = freq_hz / 1e12
        #     freq_thz = freq_hz / (2 * np.pi * 1e12)
        #     print(f"{i:3d}  {val:10.6f}  {freq_2pi_thz:10.6f}  {freq_thz:10.6f}")

        if do_frequency_analysis:
            compute_ground_state_Vpp_and_frequency(        
                x_int, v_int, eigen_data_group, mass, polar_mode_freq)
            
        if do_frequency_analysis and Field_to_plot is not None:

            idx_closest = int(np.argmin(np.abs(field_values - Field_to_plot)))

        compute_ground_state_Vpp_and_frequency(
            x_int, v_int,
            eigen_data_group,
            mass,
            polar_mode_freq,
            field_idx=idx_closest,
            field_value=field_values[idx_closest]
            )
        
              # ------------------------------------
        # DMB effective thermal relaxation rate
        # ------------------------------------
        
        # total outflow rate of each state
        gamma_out = np.sum(gamma_mat, axis=0)
        
        # equilibrium Boltzmann populations
        boltz_weights = np.exp(-energies / (k_B * Temp))
        Z = np.sum(boltz_weights)
        
        p_eq = boltz_weights / Z
        
        # thermally weighted average relaxation rate
        avg_decay_rate = np.sum(p_eq * gamma_out)
        
        # factor of 2 to match the LO convention used in dynamics.py
        avg_decay_rate *= 2.0
        
        # convert 1/fs -> THz
        avg_decay_rate_thz = avg_decay_rate * 1520 / (2 * np.pi)
        
        print(
            f"\nEffective DMB relaxation rate:"
            f"\n  <Gamma> = Σ p_n^eq Γ_n"
            f"\n  = {avg_decay_rate:.6e} 1/fs"
            f"\n  = {avg_decay_rate_thz:.6f} THz"
        )   
        
        
        # ------------------------------------
        # gamma_rescale determination
        # ------------------------------------
        
        if gamma_target_thz is not None:
        
            gamma_rescale = gamma_target_thz / avg_decay_rate_thz
        
            print(
                f"\nTarget relaxation rate:"
                f"\n  gamma_target = {gamma_target_thz:.6f} THz"
            )
        
            print(
                f"\nSuggested gamma_rescale:"
                f"\n  gamma_rescale = gamma_target / <Gamma>"
                f"\n  = {gamma_rescale:.6e}"
            )
 
             
            
            
            
     #   compute_ground_state_Vpp_and_frequency(x_int, v_int, eigen_data_group, mass, polar_mode_freq)    
    



psi2_matrix = np.column_stack(psi2_matrix)

# Combine x and all densities
data_to_save = np.column_stack([x_int, psi2_matrix])

# Create header with state numbers
header = "x " + " ".join([f"psi2_state_{i}" for i in selected_states])

np.savetxt(
    "prob_density_selected_states.txt",
    data_to_save,
    header=header
)

P_list = np.array(X_av_list) / conv_P2x
P_part_list = np.array(X_av_part_list) / conv_P2x

# Save full polarization to a text file
data_to_save = np.column_stack([field_values, P_list])
header = "Field(V/nm) P_full(C/m^2)"
np.savetxt("Polarization_vs_Field_equil.txt", data_to_save, header=header)

plt.figure(figsize=(7, 5))
plt.plot(field_values, P_list, label="Full Polarization")
plt.plot(field_values_part, P_part_list, label=f"Partial Polarization [{x_min}, {x_max}]")

plt.xlabel("Electric Field")
plt.ylabel("P (C/m²)")
plt.title(f"Polarization vs Electric Field at T = {Temp} K")

plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("Polarization_vs_Field_equil.png", dpi=300)
plt.show()

# # Plot both curves; partial only where defined
# plt.figure(figsize=(7, 5))
# plt.plot(field_values, X_av_list, label="Full Average")
# plt.plot(field_values_part, X_av_part_list, label=f"Partial Average [{x_min}, {x_max}]")
# plt.xlabel("Electric Field")
# plt.ylabel(r"$\langle x \rangle$")
# plt.title(f"$\\langle x \\rangle$ vs Electric Field at T = {Temp} K")
# plt.legend()
# plt.grid(True)
# plt.tight_layout()
# plt.savefig("X_av_and_partial_vs_Field.png", dpi=300)
# plt.show()    