"""

This script performs thermal averaging analysis of position expectation values ⟨x⟩
based on quantum eigenstate data generated by `generate.py`.

FUNCTIONALITY:
-------------
1. Loads simulation results (eigenenergies and eigenfunctions) from 
   'all_simulation_data.h5', including physical parameters such as mass, 
   number of states, and electric field values.
2. Loads the interpolation grid (x, V(x)) from 'interpolated_potential.txt'.
3. Loads analysis parameters (e.g., temperature, x_min, x_max, Field_to_plot) 
   from 'PARAMS_anal.json'.
4. Computes:
   - Full thermal average ⟨x⟩ over the entire domain.
   - Partial thermal average ⟨x⟩ over a subinterval [x_min, x_max], only if 
     the probability density in that region is non-negligible.
5. Plots ⟨x⟩ vs electric field for both full and partial intervals.
6. Optionally, at a user-specified electric field (Field_to_plot), plots 
   all eigenstates that together contribute ≥99% to the thermal probability 
   density at the given temperature.

INPUT FILES:
------------
- all_simulation_data.h5 : HDF5 file with eigenvalues/vectors and attributes.
- interpolated_potential.txt : Text file with columns x, V(x).
- PARAMS_anal.json : JSON file with analysis parameters including:
    {
        "Temp": float,
        "x_min": float,        (optional)
        "x_max": float,        (optional)
        "Field_to_plot": float (optional)
    }

OUTPUT:
-------
- X_av_and_partial_vs_Field.png : Plot of ⟨x⟩ vs Electric Field for both
  full and partial averages.
- Eigenstates_99percent.png : Plot of eigenstates that contribute ≥99% of 
  the thermal probability density at the specified Field_to_plot.

---------
"""


import numpy as np
import h5py
import json
import matplotlib.pyplot as plt

# Constants
k_B = 8.617333262145e-5  # eV/K

# Load temperature from PARAMS_anal.json
with open("PARAMS_anal.json", "r") as f_json:
    params_anal = json.load(f_json)
Temp = params_anal["Temp"]


# Load x_int  and v_int from interpolated_potential.txt

data_interp = np.loadtxt("interpolated_potential.txt")
x_int = data_interp[:, 0]
v_int = data_interp[:, 1]

x_min = params_anal.get("x_min", x_int.min())
x_max = params_anal.get("x_max", x_int.max())
#Field_to_plot = params_anal.get("Field_to_plot", None)  # <-- Add this line
Field_to_plot = float(params_anal.get("Field_to_plot", None)) if "Field_to_plot" in params_anal else None



def comp_X_av_partial(e_tmp, phi_tmp, x_min, x_max):
    mask = (x_int >= x_min) & (x_int <= x_max)
    # Compute full thermal probability density over all states and positions
    prob_density = np.zeros_like(x_int)
    Z = 0.
    e_tmp=e_tmp-e_tmp[0]
    for i in range(num_sol):
        prob = np.exp(-e_tmp[i] / (k_B * Temp))
        Z += prob
        prob_density += prob * (phi_tmp[:, i] ** 2)
    prob_density /= Z  # Normalize full probability density

    # Compute partial trace on interval
    partial_prob = np.sum(prob_density[mask])
    total_prob = np.sum(prob_density)
#    print(partial_prob/total_prob) 
    if partial_prob/total_prob > 0.001:
        # Compute partial average <x> on the interval weighted by partial prob density
        X_av_partial = np.sum(x_int[mask] * prob_density[mask]) / partial_prob
        return X_av_partial
    else:
        return None  # No weight in this interval

    # Function to compute X_av at a given field
def comp_X_av(e_tmp, phi_tmp):
    Z = 0.
    X_av = 0.
    for i in range(num_sol):
        prob = np.exp(-e_tmp[i] / (k_B * Temp))
        Z += prob
        X_av += prob * np.sum(x_int * phi_tmp[:, i] ** 2)
    return X_av / Z

# Load everything from the HDF5 file
with h5py.File("all_simulation_data.h5", "r") as f:
    mass = f.attrs['mass']
    n = int(f.attrs['n'])
    num_sol = int(f.attrs['num_sol'])
    z_star = f.attrs['Star']
    Vol = f.attrs['Vol']

    field_values = f['field_values'][:]
    eigen_data_group = f['eigen_data']

    



    # Loop over all fields and compute X_av
    X_av_list = []
    X_av_part_list = []
    field_values_part = []  # for partial points where trace > 0
    for i in range(len(field_values)):
        group = eigen_data_group[f'field_{i:03d}']
        energies = group['energies'][:]
        energies = energies - energies[0]
        eigenvectors = group['eigenvectors'][:]
        X_av = comp_X_av(energies, eigenvectors)
        X_av_part = comp_X_av_partial(energies, eigenvectors, x_min, x_max)
        if X_av_part is not None:
            X_av_part_list.append(X_av_part)
            field_values_part.append(field_values[i])
            # else skip
        X_av_list.append(X_av)
#        X_av_part_list.append(X_av_part)



    # Optional: Plot selected eigenstates at a specific field value
    #if "Field_to_plot" in params_anal:
    if Field_to_plot is not None:
        E_plot = Field_to_plot
        idx_closest = int(np.argmin(np.abs(field_values - E_plot)))  # cast to plain int
        group_name = f'field_{idx_closest:03d}'  # this will now be a valid string
        group = eigen_data_group[group_name]
        
        # Your plotting logic here
       # E_plot = params_anal["Field_to_plot"]
       # idx_closest = np.argmin(np.abs(field_values - E_plot))
       # group = eigen_data_group[f'field_{idx_closest:03d}']
        energies = group['energies'][:]
        energies = energies - energies[0]
        eigenvectors = group['eigenvectors'][:]
    
        # Compute Boltzmann weights
        boltz_weights = np.exp(-energies / (k_B * Temp))
        Z = np.sum(boltz_weights)
        probs = boltz_weights / Z
    
        # Sort states by descending probability
        sorted_indices = np.argsort(probs)[::-1]
        cumulative_prob = 0.
        selected_states = []
        for idx in sorted_indices:
            cumulative_prob += probs[idx]
            selected_states.append(idx)
            if cumulative_prob >= 0.99:
                break
    
        # Plot selected eigenstates with vertical shift by energy
        plt.figure(figsize=(8, 6))
        for idx in selected_states:
            psi = eigenvectors[:, idx]
            prob_density = psi**2
            prob_density /= np.max(prob_density)  # Normalize for visibility
            vertical_shift = energies[idx]        # Shift by eigenenergy (in eV)
            plt.plot(x_int, prob_density + vertical_shift, 
                     label=f"$E_{{{idx}}}$ = {energies[idx]:.3f} eV, p = {probs[idx]*100:.1f}%")
        
        plt.xlabel("x")
        plt.ylabel(r"$|\psi(x)|^2 + E$")
        plt.title(f"Eigenstates Contributing ≥99% at E = {field_values[idx_closest]:.3f} V/nm, T = {Temp} K")
        plt.legend()
        plt.grid(True)
        plt.tight_layout()
        plt.savefig("Eigenstates_99percent.png", dpi=300)
        plt.show()
        print("\nAll eigenvalues (index, eV, 2π·THz, THz):")
        ev_to_hz = 2.417989e14  # 1 eV = 2.417989e14 Hz
        for i, val in enumerate(energies):
            freq_hz = val * ev_to_hz
            freq_2pi_thz = freq_hz / 1e12
            freq_thz = freq_hz / (2 * np.pi * 1e12)
            print(f"{i:3d}  {val:10.6f}  {freq_2pi_thz:10.6f}  {freq_thz:10.6f}")
    
    
# Plot both curves; partial only where defined
plt.figure(figsize=(7, 5))
plt.plot(field_values, X_av_list, label="Full Average")
plt.plot(field_values_part, X_av_part_list, label=f"Partial Average [{x_min}, {x_max}]")
plt.xlabel("Electric Field")
plt.ylabel(r"$\langle x \rangle$")
plt.title(f"$\\langle x \\rangle$ vs Electric Field at T = {Temp} K")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("X_av_and_partial_vs_Field.png", dpi=300)
plt.show()    